export type {
  DesktopProcessEvent,
  DesktopProcessHandle,
  EditorHandle,
  EditorKindCapabilities,
  EditorKindInfo,
  EditorMountConfig,
  EditorSession,
  EditorSessionRange,
  PluginEventMap,
  PluginFileViewerConfig,
  PluginFileStat,
  PluginSettingChangeEvent,
  PluginSearchQueryResult,
  PluginSettingsPageConfig,
  PluginTaskStatusHandle,
  PluginWorkspaceInfo,
  SearchFileTextProvider,
  SearchFileTextProviderInput,
  VoltPluginAPI,
} from '@kernel/plugin-system/runtime/pluginApi';
