// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dialog} from '../models';

export function PickFiles(arg1:string,arg2:Array<dialog.FileFilter>,arg3:boolean):Promise<Array<string>>;

export function PickImage():Promise<string>;

export function SelectDirectory():Promise<string>;
