// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PickFiles(arg1, arg2, arg3) {
  return window['go']['wailshandler']['DialogHandler']['PickFiles'](arg1, arg2, arg3);
}

export function PickImage() {
  return window['go']['wailshandler']['DialogHandler']['PickImage']();
}

export function SelectDirectory() {
  return window['go']['wailshandler']['DialogHandler']['SelectDirectory']();
}
