// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDirectory(arg1, arg2) {
  return window['go']['wailshandler']['FileHandler']['CreateDirectory'](arg1, arg2);
}

export function CreateFile(arg1, arg2, arg3) {
  return window['go']['wailshandler']['FileHandler']['CreateFile'](arg1, arg2, arg3);
}

export function Delete(arg1, arg2) {
  return window['go']['wailshandler']['FileHandler']['Delete'](arg1, arg2);
}

export function ListTree(arg1, arg2) {
  return window['go']['wailshandler']['FileHandler']['ListTree'](arg1, arg2);
}

export function Read(arg1, arg2) {
  return window['go']['wailshandler']['FileHandler']['Read'](arg1, arg2);
}

export function Rename(arg1, arg2, arg3) {
  return window['go']['wailshandler']['FileHandler']['Rename'](arg1, arg2, arg3);
}

export function Write(arg1, arg2, arg3) {
  return window['go']['wailshandler']['FileHandler']['Write'](arg1, arg2, arg3);
}
