// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {file} from '../models';

export function CreateDirectory(arg1:string,arg2:string):Promise<void>;

export function CreateFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Delete(arg1:string,arg2:string):Promise<void>;

export function ListTree(arg1:string,arg2:string):Promise<Array<file.FileEntry>>;

export function Read(arg1:string,arg2:string):Promise<string>;

export function Rename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Write(arg1:string,arg2:string,arg3:string):Promise<void>;
