// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyImage(arg1, arg2, arg3) {
  return window['go']['wailshandler']['ImageHandler']['CopyImage'](arg1, arg2, arg3);
}

export function PickImage() {
  return window['go']['wailshandler']['ImageHandler']['PickImage']();
}

export function ReadImageBase64(arg1, arg2) {
  return window['go']['wailshandler']['ImageHandler']['ReadImageBase64'](arg1, arg2);
}

export function SaveImageBase64(arg1, arg2, arg3, arg4) {
  return window['go']['wailshandler']['ImageHandler']['SaveImageBase64'](arg1, arg2, arg3, arg4);
}
