// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {note} from '../models';
import {context} from '../models';

export function CreateDirectory(arg1:string,arg2:string):Promise<void>;

export function CreateFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateNote(arg1:string,arg2:string):Promise<void>;

export function DeleteNote(arg1:string,arg2:string):Promise<void>;

export function ListTree(arg1:string,arg2:string):Promise<Array<note.FileEntry>>;

export function ReadNote(arg1:string,arg2:string):Promise<string>;

export function RenameNote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveNote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
