// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDirectory(arg1, arg2) {
  return window['go']['wailshandler']['NoteHandler']['CreateDirectory'](arg1, arg2);
}

export function CreateFile(arg1, arg2, arg3) {
  return window['go']['wailshandler']['NoteHandler']['CreateFile'](arg1, arg2, arg3);
}

export function CreateNote(arg1, arg2) {
  return window['go']['wailshandler']['NoteHandler']['CreateNote'](arg1, arg2);
}

export function DeleteNote(arg1, arg2) {
  return window['go']['wailshandler']['NoteHandler']['DeleteNote'](arg1, arg2);
}

export function ListTree(arg1, arg2) {
  return window['go']['wailshandler']['NoteHandler']['ListTree'](arg1, arg2);
}

export function ReadNote(arg1, arg2) {
  return window['go']['wailshandler']['NoteHandler']['ReadNote'](arg1, arg2);
}

export function RenameNote(arg1, arg2, arg3) {
  return window['go']['wailshandler']['NoteHandler']['RenameNote'](arg1, arg2, arg3);
}

export function SaveNote(arg1, arg2, arg3) {
  return window['go']['wailshandler']['NoteHandler']['SaveNote'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['wailshandler']['NoteHandler']['SetContext'](arg1);
}
