// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelPluginProcess(arg1) {
  return window['go']['wailshandler']['PluginHandler']['CancelPluginProcess'](arg1);
}

export function DeletePlugin(arg1) {
  return window['go']['wailshandler']['PluginHandler']['DeletePlugin'](arg1);
}

export function GetPluginData(arg1, arg2) {
  return window['go']['wailshandler']['PluginHandler']['GetPluginData'](arg1, arg2);
}

export function ImportPluginArchive(arg1) {
  return window['go']['wailshandler']['PluginHandler']['ImportPluginArchive'](arg1);
}

export function ListPlugins() {
  return window['go']['wailshandler']['PluginHandler']['ListPlugins']();
}

export function LoadPluginSource(arg1) {
  return window['go']['wailshandler']['PluginHandler']['LoadPluginSource'](arg1);
}

export function PickPluginArchive() {
  return window['go']['wailshandler']['PluginHandler']['PickPluginArchive']();
}

export function SetContext(arg1) {
  return window['go']['wailshandler']['PluginHandler']['SetContext'](arg1);
}

export function SetPluginData(arg1, arg2, arg3) {
  return window['go']['wailshandler']['PluginHandler']['SetPluginData'](arg1, arg2, arg3);
}

export function SetPluginEnabled(arg1, arg2) {
  return window['go']['wailshandler']['PluginHandler']['SetPluginEnabled'](arg1, arg2);
}

export function StartPluginProcess(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['wailshandler']['PluginHandler']['StartPluginProcess'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
