// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plugin} from '../models';
import {context} from '../models';

export function CancelPluginProcess(arg1:string):Promise<void>;

export function DeletePlugin(arg1:string):Promise<void>;

export function GetPluginData(arg1:string,arg2:string):Promise<string>;

export function ImportPluginArchive(arg1:string):Promise<plugin.Plugin>;

export function ListPlugins():Promise<Array<plugin.Plugin>>;

export function LoadPluginSource(arg1:string):Promise<string>;

export function PickPluginArchive():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetPluginData(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetPluginEnabled(arg1:string,arg2:boolean):Promise<void>;

export function StartPluginProcess(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:string,arg6:string,arg7:string):Promise<void>;
