// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['wailshandler']['ProcessHandler']['Cancel'](arg1);
}

export function Start(arg1) {
  return window['go']['wailshandler']['ProcessHandler']['Start'](arg1);
}
