// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SearchFiles(arg1, arg2) {
  return window['go']['wailshandler']['SearchHandler']['SearchFiles'](arg1, arg2);
}
