// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';

export function GetLocalization(arg1:Array<string>):Promise<settings.LocalizationPayload>;

export function SetLocale(arg1:string,arg2:Array<string>):Promise<settings.LocalizationPayload>;
