// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocalization(arg1) {
  return window['go']['wailshandler']['SettingsHandler']['GetLocalization'](arg1);
}

export function SetLocale(arg1, arg2) {
  return window['go']['wailshandler']['SettingsHandler']['SetLocale'](arg1, arg2);
}
