// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigDir() {
  return window['go']['wailshandler']['StorageHandler']['ConfigDir']();
}

export function Delete(arg1, arg2) {
  return window['go']['wailshandler']['StorageHandler']['Delete'](arg1, arg2);
}

export function Get(arg1, arg2) {
  return window['go']['wailshandler']['StorageHandler']['Get'](arg1, arg2);
}

export function List(arg1) {
  return window['go']['wailshandler']['StorageHandler']['List'](arg1);
}

export function Set(arg1, arg2, arg3) {
  return window['go']['wailshandler']['StorageHandler']['Set'](arg1, arg2, arg3);
}
