// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';
import {storage} from '../models';

export function ConfigDir():Promise<string>;

export function Delete(arg1:string,arg2:string):Promise<void>;

export function Get(arg1:string,arg2:string):Promise<json.RawMessage>;

export function List(arg1:string):Promise<Array<storage.KVEntry>>;

export function Set(arg1:string,arg2:string,arg3:json.RawMessage):Promise<void>;
