// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateVolt(arg1, arg2) {
  return window['go']['wailshandler']['VoltHandler']['CreateVolt'](arg1, arg2);
}

export function CreateVoltInParent(arg1, arg2, arg3) {
  return window['go']['wailshandler']['VoltHandler']['CreateVoltInParent'](arg1, arg2, arg3);
}

export function DeleteVolt(arg1) {
  return window['go']['wailshandler']['VoltHandler']['DeleteVolt'](arg1);
}

export function ListVolts() {
  return window['go']['wailshandler']['VoltHandler']['ListVolts']();
}

export function SelectDirectory() {
  return window['go']['wailshandler']['VoltHandler']['SelectDirectory']();
}
